### ISSUE TITLE
alternative and configurable FilerFileField/FilerImageField

### ISSUE THREAD

**Issue by benzkji** [rouxcode/django-filer-addons#5]
options for for:

- enable/disable direct upload/dndrop
- enable/disable existing/uploaded file selection through file picker
- enable/disable removal of file
- enable/disable file edit link
- specify folder to put direct uploads into (difficult with field only!?)
- bigger thumbnail
- drop files working in inlines (new added)

Bonus

- add "click to select local file" link

**Comment by wullerot** [comment]
Needs
- Messaging system for widget
